
# gf home site cdn.
[cdn]
    url = "https://gf.cdn.johng.cn"

# home site url.
[home]
    url = "https://goframe.org"

# go proxy for gf get.
[proxy]
    urls = [
		"https://goproxy.io/",
		"https://goproxy.cn/"
	]